In [2]:
# FUngsi
def hello(n, k):
    for i in range(n):
        print(k)

In [3]:
hello(10,"Program python")

Program python
Program python
Program python
Program python
Program python
Program python
Program python
Program python
Program python
Program python


In [5]:
# fungsi membalikkan sebuah nilai 
def faktorial(n):
    i=1
    result = 1
    while i < n:
        result = result * n
        n = n -1
    
    return result 

In [7]:
hasil = faktorial(3)
print(hasil)

6


# 2. File INPUT OUTPUT

In [8]:
f = open('data.txt','w')
f.write('Hello world !  \n')
f.write('Something in second line !  \n')
f.write('sentence in third line  \n')
f.write('end blah blah line  \n')
f.close()

In [9]:
fo = open('data.txt','r')
print(fo.read())
fo.close()

Hello world !  
Something in second line !  
sentence in third line  
end blah blah line  



In [10]:
fo = open('data.txt','r')
for i in fo:
    print('===============')
    print(i.lower())
fo.close()

hello world !  

something in second line !  

sentence in third line  

end blah blah line  



# 3. Import

In [15]:
# Random
import random
r = random.random()
print(r)

r = random.randint(1,10)
print(r)

0.14062194086618174
2


In [21]:
import statistics

a = [0,1,1,3,4,9,15]
b = statistics.mean(a)
c = statistics.median(a)
d = statistics.mode(a)

print(a,b,c,d)

[0, 1, 1, 3, 4, 9, 15] 4.714285714285714 3 1


In [ ]:
dir(statistics)

# Modul CSV

In [22]:
import csv

#penggunaan with ... as namavariabel
#  memastikan bahwa fungsi open file langsung di closed agar memory kembali kosong



In [26]:
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)

[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
(2, 3)


In [27]:
c = np.zeros((2,2))
print(c)



[[0. 0.]
 [0. 0.]]


In [28]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2, 1:3]  # baris awal s.d. baris ke 2, dan kolom indeks-ke-1 sd kolom ke-3
print(b)
# print(a[0, 1])   
# b[0, 0] = 77     
# print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [30]:
import pandas as pd

In [32]:
data_kekeringan = pd.read_csv('data-bencana-kekeringan-2012-2013.csv',delimiter =',', encoding = "ISO-8859-1")

In [35]:
# data_kekeringan
# data_kekeringan.head()
data_kekeringan.sample(5)

No     Bencana    Tanggal        Jam    Bujur   Lintang   \
13   14  Kekeringan   9/5/2013        NaN  113.994  -7.70555   
8     9  Kekeringan  9/17/2013        NaN  108.214  -7.32795   
14   15  Kekeringan   9/2/2013          -  106.551  -6.98727   
18   19  Kekeringan  8/31/2013        NaN  109.547  -7.46168   
1     2  Kekeringan  9/23/2013  12.30 WIB  106.842  -6.17332   

                                              Lokasi   \
13  Dsn.Krajan Dsn.Jambaran Dsn.Kembang Sari Timur...   
8               Kab. Tasikmalaya, Provinsi Jawa Barat   
14  Kec. Tegal Buleud Ds. Calincing Kp. Puncak Sob...   
18  Ds panerusan kulon Ds Panerusan wetan Ds gumel...   
1   Jl. Krmat III Dalam RT. 06 / 08 Kel. Kwitang K...   

                                              Korban   \
13                                              Nihil   
8                               Masih dalam pendataan   
14  Korban Jiwa/Terdampak : • Ds. Pagelaran 700 KK...   
18                                              Nihil   
1                                               nihil   

                                            Kerugian   \
13                                              Nihil   
8                               Masih dalam pendataan   
14  Kerugian Materil : • Di Kec. Jampang Kulon, Ds...   
18  -Sawah 304 Ha Kering terancam gagal panen -Lad...   
1                                    1 rumah terbakar   

                                          Keterangan   
13  Kondisi Muktahir: -Jarak lokasi ke kota 20 Kmâ...  
8   Kronologis : - Disebabkan oleh Musim Kemarau U...  
14  Kronologis : Kekeringan terjadi pada akhir Agu...  
18  Kronologis : -Jumlah desa yang mengalami rawan...  
1   Kronologis : - Api berasal dari Korsleting aru...

In [36]:
data_kekeringan.columns

Index(['No ', 'Bencana ', 'Tanggal ', 'Jam ', 'Bujur ', 'Lintang ', 'Lokasi ',
       'Korban ', 'Kerugian ', 'Keterangan '],
      dtype='object')

In [37]:
data_kekeringan[['Bencana ','Lokasi ']]

Bencana                                             Lokasi 
0   Kekeringan  Kampung Laut Kawungaten Kedungmangu Gadingreja...
1   Kekeringan  Jl. Krmat III Dalam RT. 06 / 08 Kel. Kwitang K...
2   Kekeringan  Jl. Cibubur, Blok Dukuh, No. 6 RT. 02 / 10 Kel...
3   Kekeringan  Jl. Kebon Tebu RT. 019 / 17 Kel. Muara Baru Ke...
4   Kekeringan  Provinsi Jawa Barat Kota Cirebon Kec. Harjamuk...
5   Kekeringan  Ds. Bujur Barat Ds. Bujur Timur Ds. Ponjanan B...
6   Kekeringan  Ds. Sruwi Ds. Sumberejo Kec. Winongan Ds. Kara...
7   Kekeringan  Ds. Sruwi Ds. Sumberejo Kec. Winongan Ds. Kara...
8   Kekeringan              Kab. Tasikmalaya, Provinsi Jawa Barat
9   Kekeringan  Provinsi Jawa Barat Kab. Bandung Barat Kec Lem...
10  Kekeringan                    Provinsi Jawa Barat Kab. Ciamis
11  Kekeringan  (83 Desa dalam pendataan) Kec. Kebumen Kec. Ka...
12  Kekeringan  Provinsi Jawa Barat Kab. Bandung Kec. Bojong S...
13  Kekeringan  Dsn.Krajan Dsn.Jambaran Dsn.Kembang Sari Timur...
14  Kekeringan  Kec. Tegal Buleud Ds. Calincing Kp. Puncak Sob...
15  Kekeringan  Kec. Nglegok Ds. Sumber Sari Kec. Panggung Rej...
16  Kekeringan  Ds. Kamal Ds. Pamulihan Kec. Larangan Ds. Peng...
17  Kekeringan  Kec. Bagelen Kec. Purworejo Kec. Gerabak Kec. ...
18  Kekeringan  Ds panerusan kulon Ds Panerusan wetan Ds gumel...
19  Kekeringan  Kec. Ayah Kec. Buayan Kec. Rowokele Kec. Sempo...
20  Kekeringan  Kec. Simpang Empat, Kab. Banjar, Prov. Kaliman...
21  Kekeringan                 Kab. Probolinggo, Prov. Jawa Timur
22  Kekeringan  Kec. Gempol dan Lumbang, Kab. Pasuruan, Prov. ...

In [53]:
data_kekeringan[['Bencana ','Lokasi ']].head(2)

Bencana                                             Lokasi 
0  Kekeringan  Kampung Laut Kawungaten Kedungmangu Gadingreja...
1  Kekeringan  Jl. Krmat III Dalam RT. 06 / 08 Kel. Kwitang K...

In [54]:
data_pangan = pd.read_csv('jumlah-usaha-pertanian-per-provinsi-per-usaha-2003-2013.csv', delimiter = ',', encoding = "utf-8")

In [55]:
data_pangan.count()

kode_provinsi    165
nama_provinsi    170
bentuk_usaha     170
tahun            170
jumlah           169
dtype: int64

In [56]:
data_pangan.columns

Index(['kode_provinsi', 'nama_provinsi', 'bentuk_usaha', 'tahun', 'jumlah'], dtype='object')